WebsitePresentation/Areas/AdministratorArea/Controllers/HomeAdminController.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using WebsitePresentation.Controllers;

namespace WebsitePresentation.Areas.AdministratorArea.Controllers
{
    [Area("AdministratorArea")]
    [Authorize(Roles = "Admin,Administrator")]
    public class HomeAdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ServiceAdminControl _serviceAdminControl;

        public HomeAdminController(ILogger<HomeController> logger, ServiceAdminControl serviceAdminControl)
        {
            _logger = logger;
            _serviceAdminControl = serviceAdminControl; 
        }
        public IActionResult Index()
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            ViewBag.WebsiteTitle = _serviceAdminControl.WebsiteTitle();
            _logger.LogInformation(CultureInfo.CurrentCulture.Name);
            return RedirectToAction("Index", "SectionFirstSteps");
        }
    }
}

WebsitePresentation/Areas/AdministratorArea/Controllers/RoleManagerController.cs
using DataAccess.Data;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebsitePresentation.Areas.AdministratorArea.Controllers
{
    [Area("AdministratorArea")]
    [Authorize(Roles = "Administrator")]
    public class RoleManagerController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private readonly ServiceAdminControl _serviceAdminControl;
        public RoleManagerController(RoleManager<IdentityRole> roleManager, ApplicationDbContext context, ServiceAdminControl serviceAdminControl)
        {
            _roleManager = roleManager;
            _context = context;
            _serviceAdminControl = serviceAdminControl;
        }
        public async Task<IActionResult> Index()
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }
        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (roleName != null)
            {
                await _roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(string Name)
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (Name == null)
            {
                return NotFound();
            }
            var roles = await _roleManager.Roles.FirstOrDefaultAsync(m => m.Name == Name);
            return View(roles);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string Name)
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (Name != null)
            {
                var roles =  _roleManager.Roles.FirstOrDefault(m => m.Name == Name);
                await _roleManager.DeleteAsync(roles!);
            }
            return RedirectToAction("Index");
        }
    }
}

WebsitePresentation/Areas/AdministratorArea/Controllers/UserRolesController.cs
using DataAccess.Data;
using DataAccess.Services;
using DataAccess.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace WebsitePresentation.Areas.AdministratorArea.Controllers
{
    [Area("AdministratorArea")]
    [Authorize(Roles = "Administrator")]
    public class UserRolesController : Controller
    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private readonly ServiceAdminControl _serviceAdminControl;
        public UserRolesController(UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager, ApplicationDbContext context, ServiceAdminControl serviceAdminControl)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _context = context;
            _serviceAdminControl = serviceAdminControl;
        }
        public async Task<IActionResult> Index()
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            var users = await _userManager.Users.ToListAsync();
            var userRolesViewModel = new List<UserRolesViewModel>();
            foreach (IdentityUser user in users)
            {
                var thisViewModel = new UserRolesViewModel();
                thisViewModel.UserId = user.Id;
                thisViewModel.Email = user.Email;
                thisViewModel.Roles = await GetUserRoles(user);
                userRolesViewModel.Add(thisViewModel);
            }
            return View(userRolesViewModel);
        }
        private async Task<List<string>> GetUserRoles(IdentityUser user)
        {
            return new List<string>(await _userManager.GetRolesAsync(user));
        }
        public async Task<IActionResult> Manage(string userId)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            ViewBag.userId = userId;
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            ViewBag.UserName = user.UserName;
            var model = new List<ManageUserRolesViewModel>();
            foreach (var role in _roleManager.Roles)
            {
                var userRolesViewModel = new ManageUserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }
                model.Add(userRolesViewModel);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Manage(List<ManageUserRolesViewModel> model, string userId)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            var user = await _userManager.FindByIdAsync(userId);
            if (user == null)
            {
                return View();
            }
            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove user existing roles");
                return View(model);
            }
            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.Selected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected roles to user");
                return View(model);
            }
            return RedirectToAction("Index");
        }
    }
}

WebsitePresentation/Areas/AdministratorArea/Views/Shared/ErrorReportView.cshtml
@{
    ViewData["Title"] = "ErrorReportView";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}
<h4>کێشەی کۆنتڕڕۆل</h4>
<div class="row">
    <div class="col-md-12">
        @ViewData["ErrorReportMessage"]
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebsitePresentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/sitelarge.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sitemedium.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sitesmall.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/siteforall.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebsitePresentation.styles.css" asp-append-version="true" />
    <script src="~/js/ckeditor/ckeditor.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">گەڕانەوە بۆ ماڵپەری سەرەکی</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="HomeAdmin" asp-action="Index" asp-area="AdministratorArea">بابەتەکان</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="SectionPostTypes" asp-action="Index" asp-area="AdministratorArea">جۆری پۆستەکان</a>
                        </li>
                        @if (User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="RoleManager" asp-action="Index" asp-area="AdministratorArea">جۆری دەسەڵاتەکان</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="UserRoles" asp-action="Index" asp-area="AdministratorArea">بەرێوبەری دەسەڵاتەکان</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="WebsiteThemControls" asp-action="Index" asp-area="AdministratorArea">بەرێوبەری شێوەی سایت</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="WebsiteAdminsControls" asp-action="Index" asp-area="AdministratorArea">بەرێوبەری کاتی کارابوونی ئەدمینەکان</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="WebsiteActiveTimeControls" asp-action="Index" asp-area="AdministratorArea">بەرێوبەری کاتی کارابوونی سایت</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>