WebsitePresentation/Areas/AdministratorArea/Controllers/HomeAdminController.cs
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Globalization;
using WebsitePresentation.Controllers;

namespace WebsitePresentation.Areas.AdministratorArea.Controllers
{
    [Area("AdministratorArea")]
    [Authorize(Roles = "Admin,Administrator")]
    public class HomeAdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ServiceAdminControl _serviceAdminControl;

        public HomeAdminController(ILogger<HomeController> logger, ServiceAdminControl serviceAdminControl)
        {
            _logger = logger;
            _serviceAdminControl = serviceAdminControl; 
        }
        public IActionResult Index()
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            ViewBag.WebsiteTitle = _serviceAdminControl.WebsiteTitle();
            _logger.LogInformation(CultureInfo.CurrentCulture.Name);
            return RedirectToAction("Index", "SectionFirstSteps");
        }
    }
}

WebsitePresentation/Areas/ArmyMembersArea/Controllers/ArmyMembersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Data;
using Model;
using Microsoft.AspNetCore.Authorization;
using DataAccess.Services;
using X.PagedList;
using System.Collections.Immutable;

namespace WebsitePresentation.Areas.ArmyMembersArea.Controllers
{
    [Area("ArmyMembersArea")]
    [Authorize(Roles = "Administrator,ArmyAdmin,ArmyAdminRegister")]
    public class ArmyMembersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ServiceAdminControl _serviceAdminControl;
        public ArmyMembersController(ApplicationDbContext context, ServiceAdminControl serviceAdminControl)
        {
            _context = context;
            _serviceAdminControl = serviceAdminControl;
        }

        // GET: ArmyMembersArea/ArmyMembers
        public async Task<IActionResult> Index(int? page)
        {
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            var pageNumber = page ?? 1; // if no page is specified, default to the first page (1)
            int PageSize = 50;
           IEnumerable<ArmyMembers> armyMembers = await _context.ArmyMembers!.OrderByDescending(m=>m.CreateDate).ToListAsync();
            return _context.ArmyMembers != null ? 
                          View( armyMembers.ToPagedList(pageNumber, PageSize)) :
                          Problem("Entity set 'ApplicationDbContext.ArmyMembers'  is null.");
        }

        // GET: ArmyMembersArea/ArmyMembers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //Check Admin WorkTime
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.ArmyMembers == null)
            {
                return NotFound();
            }

            var armyMembers = await _context.ArmyMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (armyMembers == null)
            {
                return NotFound();
            }

            return View(armyMembers);
        }

        // GET: ArmyMembersArea/ArmyMembers/Create
        public IActionResult Create()
        {
            //Check Admin WorkTime

            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            return View();
        }

        // POST: ArmyMembersArea/ArmyMembers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Add,Administrator,FullWriter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,MemberEmail,TellNumber,Id,Active,Timable,StartDate,EndDate,CreateDate,Email,TagsName")] ArmyMembers armyMembers)
        {
            //Check Admin WorkTime

            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (ModelState.IsValid)
            {
                armyMembers.Email = User.Identity!.Name;
                _context.Add(armyMembers);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(armyMembers);
        }

        // GET: ArmyMembersArea/ArmyMembers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //Check Admin WorkTime

            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.ArmyMembers == null)
            {
                return NotFound();
            }

            var armyMembers = await _context.ArmyMembers.FindAsync(id);
            if (armyMembers == null)
            {
                return NotFound();
            }
            return View(armyMembers);
        }

        // POST: ArmyMembersArea/ArmyMembers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Edit,Administrator,FullWriter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,MemberEmail,TellNumber,Id,Active,Timable,StartDate,EndDate,CreateDate,Email,TagsName")] ArmyMembers armyMembers)
        {
            //Check Admin WorkTime

            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id != armyMembers.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(armyMembers);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArmyMembersExists(armyMembers.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(armyMembers);
        }

        // GET: ArmyMembersArea/ArmyMembers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //Check Admin WorkTime

            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.ArmyMembers == null)
            {
                return NotFound();
            }

            var armyMembers = await _context.ArmyMembers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (armyMembers == null)
            {
                return NotFound();
            }

            return View(armyMembers);
        }

        // POST: ArmyMembersArea/ArmyMembers/Delete/5
        [Authorize(Roles = "Delete,Administrator,FullWriter")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //Check Admin WorkTime

            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (_context.ArmyMembers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ArmyMembers'  is null.");
            }
            var armyMembers = await _context.ArmyMembers.FindAsync(id);
            if (armyMembers != null)
            {
                _context.ArmyMembers.Remove(armyMembers);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArmyMembersExists(int id)
        {
          return (_context.ArmyMembers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebsitePresentation/Areas/ArmyMembersArea/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebsitePresentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/sitelarge.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sitemedium.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sitesmall.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/siteforall.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebsitePresentation.styles.css" asp-append-version="true" />
    <script src="~/js/ckeditor/ckeditor.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">گەڕانەوە بۆ ماڵپەری سەرەکی</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*  <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="HomeAdmin" asp-action="Index" asp-area="AdministratorArea">بابەتەکان</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="SectionPostTypes" asp-action="Index" asp-area="AdministratorArea">جۆری پۆستەکان</a>
                        </li>*@
                        @if (User.IsInRole("ArmyAdmin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="ArmyMembersArea" asp-controller="ArmyMembers" asp-action="Index" asp-area="AdministratorArea">ئەندامان</a>
                            </li>
                            @*  <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="ArmyMembersArea" asp-controller="ArmyMembersAccounts" asp-action="Index" asp-area="AdministratorArea">ئەکاونت</a>
                        </li>*@

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="ArmyMembersArea" asp-controller="ArmyPostDetails" asp-action="Index" asp-area="AdministratorArea">کۆنتڕۆڵی پۆستەکان</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="ArmyMembersArea" asp-controller="ArmySocialsNames" asp-action="Index" asp-area="AdministratorArea">جۆری سۆشیال میدیا</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>