WebsitePresentation/Areas/AdministratorArea/Controllers/SectionPostImagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataAccess.Data;
using Model;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using DataAccess.Services;

namespace WebsitePresentation.Areas.AdministratorArea.Controllers
{
    [Area("AdministratorArea")]
    [Authorize(Roles = "Admin,Administrator")]
    public class SectionPostImagesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ServiceAdminControl _serviceAdminControl;
        [Obsolete]
        private readonly IHostingEnvironment _env;

        [Obsolete]
        public SectionPostImagesController(ApplicationDbContext context, IHostingEnvironment env, ServiceAdminControl serviceAdminControl)
        {
            _context = context;
            _env = env;
            _serviceAdminControl = serviceAdminControl;
        }

        // GET: AdministratorArea/SectionPostImages
        public async Task<IActionResult> Index(int? idTemp)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            ViewBag.idTemp = idTemp;
            if (idTemp != null)
            {
                var applicationDbContext = _context.SectionPostImages!.Where(m => m.Id_SectionPostStep == idTemp).OrderByDescending(m => m.CreateDate).Include(s => s.SectionPostStep);
                var ParentDetail = _context.SectionPostSteps!.Find(idTemp);
                ViewBag.ParentDetail = ParentDetail!.Id + "-" + ParentDetail!.Title;
                return View(await applicationDbContext.ToListAsync());
            }
            return RedirectToAction("Index", "SectionFirstSteps");
        }

        // GET: AdministratorArea/SectionPostImages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.SectionPostImages == null)
            {
                return NotFound();
            }

            var sectionPostImage = await _context.SectionPostImages
                .Include(s => s.SectionPostStep)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sectionPostImage == null)
            {
                return NotFound();
            }

            return View(sectionPostImage);
        }

        // GET: AdministratorArea/SectionPostImages/Create
        public IActionResult Create(int? idTemp)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            ViewBag.idTemp = idTemp;
            if (idTemp != null)
            {
                ViewData["Id_SectionPostStep"] = new SelectList(_context.SectionPostSteps!.Where(m => m.Id == idTemp), "Id", "Title");
                return View();
            }
            return RedirectToAction("Index", "SectionFirstSteps");
        }

        // POST: AdministratorArea/SectionPostImages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Add,Administrator,FullWriter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Create(List<IFormFile> files, [Bind("Title,Id_SectionPostStep,Id,Active,Timable,StartDate,EndDate,TagsName"),] SectionPostImage sectionPostImage, int idTemp)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (ModelState.IsValid)
            {
                sectionPostImage.Email = User.Identity!.Name;
                long size = files.Sum(f => f.Length);
                var filePaths = new List<string>();
                foreach (var formFile in files)
                {
                    if (formFile.Length > 0)
                    {
                        // full path to file in temp location
                        string newFilename = sectionPostImage.Id_SectionPostStep + "-" + Guid.NewGuid().ToString() + Path.GetExtension(formFile.FileName);
                        string filePath = Path.Combine(_env.WebRootPath, "Images", "ImageLarge", newFilename);
                        filePaths.Add(filePath);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await formFile.CopyToAsync(stream);
                        }
                        SectionPostImage sectionPostImageForAll = new SectionPostImage();
                        sectionPostImageForAll.Id_SectionPostStep = sectionPostImage.Id_SectionPostStep;
                        sectionPostImageForAll.Active = sectionPostImage.Active;
                        sectionPostImageForAll.Timable = sectionPostImage.Timable;
                        sectionPostImageForAll.Title = sectionPostImage.Title;
                        sectionPostImageForAll.Email = sectionPostImage.Email;
                        sectionPostImageForAll.StartDate = sectionPostImage.StartDate;
                        sectionPostImageForAll.EndDate = sectionPostImage.EndDate;
                        sectionPostImageForAll.TagsName = sectionPostImage.TagsName;
                        sectionPostImageForAll.Email = sectionPostImage.Email;
                        sectionPostImageForAll.PictureAddress = newFilename;
                        _context.Add(sectionPostImageForAll);
                        await _context.SaveChangesAsync();
                    }
                }
                return RedirectToAction("Index", new { @idTemp = sectionPostImage.Id_SectionPostStep });
            }
            ViewBag.idTemp = idTemp;
            ViewData["Id_SectionPostStep"] = new SelectList(_context.SectionPostSteps!.Where(m => m.Id == sectionPostImage.Id_SectionPostStep), "Id", "Title", sectionPostImage.Id_SectionPostStep);
            return View(sectionPostImage);
        }

        // GET: AdministratorArea/SectionPostImages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.SectionPostImages == null)
            {
                return NotFound();
            }

            var sectionPostImage = await _context.SectionPostImages.FindAsync(id);
            if (sectionPostImage == null)
            {
                return NotFound();
            }
            ViewData["Id_SectionPostStep"] = new SelectList(_context.SectionPostSteps!.Where(m => m.Id == sectionPostImage.Id_SectionPostStep), "Id", "Title", sectionPostImage.Id_SectionPostStep);
            return View(sectionPostImage);
        }

        // POST: AdministratorArea/SectionPostImages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Edit,Administrator,FullWriter")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,PictureAddress,Id_SectionPostStep,Id,Active,Timable,StartDate,EndDate,CreateDate,Email,TagsName")] SectionPostImage sectionPostImage)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id != sectionPostImage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sectionPostImage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SectionPostImageExists(sectionPostImage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Id_SectionPostStep"] = new SelectList(_context.SectionPostSteps, "Id", "Title", sectionPostImage.Id_SectionPostStep);

WebsitePresentation/Areas/AdministratorArea/Views/SectionPostImages/Create.cshtml
@model Model.SectionPostImage

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}

        <h4>زیادکردن-وێنە بۆ پۆست</h4>
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="Id_SectionPostStep" class="control-label"></label>
                    <select asp-for="Id_SectionPostStep" class="form-control" asp-items="ViewBag.Id_SectionPostStep" disabled></select>
                </div>
            </div>
        </div>
<div class="row">
    <div class="col-md-12">
        <form method="post" enctype="multipart/form-data" asp-controller="SectionPostImages" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                        </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Timable" /> @Html.DisplayNameFor(model => model.Timable)
                        </label>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="TagsName" class="control-label"></label>
                        <input asp-for="TagsName" class="form-control" />
                        <span asp-validation-for="TagsName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label">وێنەکان هەڵبژێرە</label>
                        <input type="file" name="files" multiple />
                    </div>
                </div>
            </div>
            <input type="hidden" id="idTemp" name="idTemp" value="@ViewBag.idTemp" />
            <select asp-for="Id_SectionPostStep" class="form-control" asp-items="ViewBag.Id_SectionPostStep" hidden></select>

            <div class="form-group">
                <input type="submit" value="ناردن" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index" asp-controller="SectionPostImages" asp-route-idTemp="@ViewBag.idTemp">گەڕانەوە بۆ لیست</a>
            </div>
        </form>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/SectionPostImages/Delete.cshtml
@model Model.SectionPostImage

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}

<h4>دیتن-وێنە بۆ پۆست</h4>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PictureAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PictureAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SectionPostStep)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SectionPostStep!.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Timable)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Timable)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TagsName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TagsName)
        </dd>
    </dl>
    <div class="row">
        <div class="col-md-2">
            <h5>دڵنیایی لە لابردنی؟</h5>
        </div>
        <div class="col-md-4">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="لابردن" class="btn btn-danger" />
                <a class="btn btn-info" asp-route-idTemp="@Model?.Id_SectionPostStep" asp-action="Index">گەڕانەوە بۆ لیست</a>
            </form>
        </div>
    </div>

</div>

WebsitePresentation/Areas/AdministratorArea/Views/SectionPostImages/Details.cshtml
@model Model.SectionPostImage

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
    var imgaddress = "";
    imgaddress = @"/Images/ImageLarge/" + Model.PictureAddress;

}


<h4>دیتن-وێنە بۆ پۆست</h4>

<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PictureAddress)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PictureAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.Label("وێنە")
        </dt>
        <dd class="col-sm-10">
            <img src="@imgaddress" style="width:100px;height:100px;border-radius:5px;">
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SectionPostStep)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SectionPostStep!.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Timable)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Timable)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TagsName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TagsName)
        </dd>
    </dl>
</div>
<div>
    <div class="row">
        <div class="col-md-4">
            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model?.Id">گۆڕین</a> |
            <a class="btn btn-info" asp-action="Index" asp-route-idTemp="@Model!.Id_SectionPostStep">گەڕانەوە بۆ لیست</a>
        </div>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/SectionPostImages/Edit.cshtml
@model Model.SectionPostImage

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}

<h4>گۆڕین-وێنە بۆ پۆست</h4>
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label asp-for="Id_SectionPostStep" class="control-label"></label>
            <select asp-for="Id_SectionPostStep" class="form-control" asp-items="ViewBag.Id_SectionPostStep" disabled></select>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                        </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Timable" /> @Html.DisplayNameFor(model => model.Timable)
                        </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="CreateDate" class="control-label"></label>
                        <input asp-for="CreateDate" class="form-control" />
                        <span asp-validation-for="CreateDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">

                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="TagsName" class="control-label"></label>
                        <input asp-for="TagsName" class="form-control" />
                        <span asp-validation-for="TagsName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="PictureAddress" class="control-label"></label>
                        <input asp-for="PictureAddress" class="form-control" />
                        <span asp-validation-for="PictureAddress" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <select asp-for="Id_SectionPostStep" class="form-control" asp-items="ViewBag.Id_SectionPostStep" hidden></select>
            <div class="form-group">
                <input type="submit" value="دانان" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index" asp-route-idTemp="@Model!.Id_SectionPostStep">گەڕانەوە بۆ لیست</a>
            </div>
        </form>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/SectionPostImages/Index.cshtml
@model IEnumerable<Model.SectionPostImage>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
    int idTemp = @ViewBag.idTemp;
    var imgaddress = "";
}

<h5>وێنەکان<a asp-action="Create" asp-route-idTemp="@idTemp" class="fa fa-plus"></a></h5>
@if (@ViewBag.idTemp != null)
{
    <h5>@ViewBag.ParentDetail</h5>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.Label("وێنە")
            </th>
            <th>
                @Html.Label("ناوی سەردەستە")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            imgaddress = @"/Images/ImageLarge/" + item.PictureAddress;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <img src="@imgaddress" style="width:30px;height:30px;border-radius:5px;">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SectionPostStep!.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timable)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="fa fa-edit"> </a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="fa fa-book"> </a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="fa fa-trash"> </a>
                </td>
            </tr>
        }
    </tbody>
</table>