WebsitePresentation/Areas/AdministratorArea/Controllers/WebsiteAdminsControlsController.cs
using DataAccess.Data;
using DataAccess.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Model;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace WebsitePresentation.Areas.AdministratorArea.Controllers
{
    //IN Case Limited Admin Add Admin Detail,Empty is Equal to Admin Not Limited
    [Area("AdministratorArea")]
    [Authorize(Roles = "Administrator")]
    public class WebsiteAdminsControlsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ServiceAdminControl _serviceAdminControl;
        [ObsoleteAttribute("ناردنی فایل")]
        private readonly IHostingEnvironment _env;

        [ObsoleteAttribute("ناردنی فایل")]
        public WebsiteAdminsControlsController(ApplicationDbContext context, IHostingEnvironment env, ServiceAdminControl serviceAdminControl)
        {
            _context = context;
            _env = env;
            _serviceAdminControl = serviceAdminControl;
        }

        // GET: AdministratorArea/WebsiteAdminsControls
        public async Task<IActionResult> Index()
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            return View(await _context.WebsiteAdminsControls!.OrderByDescending(m => m.CreateDate).ToListAsync());
        }

        // GET: AdministratorArea/WebsiteAdminsControls/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.WebsiteAdminsControls == null)
            {
                return NotFound();
            }

            var websiteAdminsControl = await _context.WebsiteAdminsControls
                .FirstOrDefaultAsync(m => m.Id == id);
            if (websiteAdminsControl == null)
            {
                return NotFound();
            }

            return View(websiteAdminsControl);
        }

        // GET: AdministratorArea/WebsiteAdminsControls/Create
        public IActionResult Create()
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            return View();
        }

        // POST: AdministratorArea/WebsiteAdminsControls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ObsoleteAttribute("ناردنی فایل")]
        public async Task<IActionResult> Create(IFormFile files, [Bind("Title,ShortDescription,FullDescription,TellphoneNmber,PictureAddress,Id,Active,Timable,StartDate,EndDate,Email,TagsName")] WebsiteAdminsControl websiteAdminsControl)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (ModelState.IsValid)
            {
                if (files.Length > 0)
                {
                    // full path to file in temp location
                    string newFilename = websiteAdminsControl.TellphoneNmber + "-" + Guid.NewGuid().ToString() + Path.GetExtension(files.FileName);
                    string filePath = Path.Combine(_env.WebRootPath, "Images", "ImageAdmin", newFilename);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await files.CopyToAsync(stream);
                    }
                    websiteAdminsControl.PictureAddress = newFilename;
                    _context.Add(websiteAdminsControl);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }

                _context.Add(websiteAdminsControl);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(websiteAdminsControl);
        }

        // GET: AdministratorArea/WebsiteAdminsControls/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.WebsiteAdminsControls == null)
            {
                return NotFound();
            }

            var websiteAdminsControl = await _context.WebsiteAdminsControls.FindAsync(id);
            if (websiteAdminsControl == null)
            {
                return NotFound();
            }
            return View(websiteAdminsControl);
        }

        // POST: AdministratorArea/WebsiteAdminsControls/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,ShortDescription,FullDescription,TellphoneNmber,PictureAddress,Id,Active,Timable,StartDate,EndDate,CreateDate,Email,TagsName")] WebsiteAdminsControl websiteAdminsControl)
        {

            if (id != websiteAdminsControl.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(websiteAdminsControl);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WebsiteAdminsControlExists(websiteAdminsControl.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(websiteAdminsControl);
        }

        // GET: AdministratorArea/WebsiteAdminsControls/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (id == null || _context.WebsiteAdminsControls == null)
            {
                return NotFound();
            }

            var websiteAdminsControl = await _context.WebsiteAdminsControls
                .FirstOrDefaultAsync(m => m.Id == id);
            if (websiteAdminsControl == null)
            {
                return NotFound();
            }

            return View(websiteAdminsControl);
        }

        // POST: AdministratorArea/WebsiteAdminsControls/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //Check Admin WorkTime
            
            if (!_serviceAdminControl.CheckAdmin(User.Identity!.Name!))
            {
                ViewData["ErrorReportMessage"] = "بەکارهێنەری بەرێز ئاکانتەکەتان ڕاگیراوە یا کاتی بەسەر چووە تکایە پەیوەندی بە بەرپرسانەوە بگرە.";
                return View("ErrorReportView");
            }
            if (_context.WebsiteAdminsControls == null)
            {
                return Problem("Entity set 'ApplicationDbContext.WebsiteAdminsControls'  is null.");
            }
            var websiteAdminsControl = await _context.WebsiteAdminsControls.FindAsync(id);
            if (websiteAdminsControl != null)
            {
                _context.WebsiteAdminsControls.Remove(websiteAdminsControl);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WebsiteAdminsControlExists(int id)
        {
            return _context.WebsiteAdminsControls!.Any(e => e.Id == id);
        }
    }
}

WebsitePresentation/Areas/AdministratorArea/Views/WebsiteAdminsControls/Create.cshtml
@model Model.WebsiteAdminsControl

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}

<h4>زیادکردن-کاتی کارابوونی ئەدمین</h4>


<div class="row">
    <div class="col-md-12">
        <form method="post" enctype="multipart/form-data" asp-controller="WebsiteAdminsControls" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                        </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Timable" /> @Html.DisplayNameFor(model => model.Timable)
                        </label>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TagsName" class="control-label"></label>
                        <input asp-for="TagsName" class="form-control" />
                        <span asp-validation-for="TagsName" class="text-danger"></span>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="ShortDescription" class="control-label"></label>
                        <input asp-for="ShortDescription" class="form-control" />
                        <span asp-validation-for="ShortDescription" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TellphoneNmber" class="control-label"></label>
                        <input asp-for="TellphoneNmber" class="form-control" />
                        <span asp-validation-for="TellphoneNmber" class="text-danger"></span>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="FullDescription" class="control-label"></label>
                        <input asp-for="FullDescription" class="form-control" />
                        <span asp-validation-for="FullDescription" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label class="control-label">وێنە هەڵبژێرە</label>
                        <input type="file" name="files" />
                    </div>
                </div>
            </div>


            <div class="form-group">
                <input type="submit" value="زیادکردن" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">گەڕانەوە بۆ لیست</a>
            </div>
        </form>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/WebsiteAdminsControls/Delete.cshtml
@model Model.WebsiteAdminsControl

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}

<h4>دیتن-بەشەکان</h4
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TellphoneNmber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TellphoneNmber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PictureAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PictureAddress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TagsName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TagsName)
        </dd>
    </dl>
    
    <div class="row">
        <div class="col-md-2">
            <h5>دڵنیایی لە لابردنی؟</h5>
        </div>
        <div class="col-md-4">
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="لابردن" class="btn btn-danger" />
                <a class="btn btn-info" asp-action="Index">گەڕانەوە بۆ لیست</a>
            </form>
        </div>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/WebsiteAdminsControls/Details.cshtml
@model Model.WebsiteAdminsControl

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
    var imgaddress = "";
    imgaddress = @"/Images/ImageAdmin/" + Model.PictureAddress;
}

<h4>دیتن-کاتی کارابوونی ئەدمین</h4>
<div>
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TellphoneNmber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TellphoneNmber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PictureAddress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PictureAddress)
        </dd>
        <dt class="col-sm-2">
            @Html.Label("وێنە")
        </dt>
        <dd class="col-sm-10">
            <img src="@imgaddress" style="width:100px;height:100px;border-radius:5px;">
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timable)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timable)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TagsName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TagsName)
        </dd>
    </dl>
</div>
<div>
    <div class="row">
        <div class="col-md-4">
            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@Model?.Id">گۆڕین</a> |
            <a class="btn btn-info" asp-action="Index">گەڕانەوە بۆ لیست</a>
        </div>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/WebsiteAdminsControls/Edit.cshtml
@model Model.WebsiteAdminsControl

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
}

<h4>گۆڕین-کاتی کارابوونی ئەدمین</h4>
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                        </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group form-check">
                        <label class="form-check-label">
                            <input class="form-check-input" asp-for="Timable" /> @Html.DisplayNameFor(model => model.Timable)
                        </label>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="CreateDate" class="control-label"></label>
                        <input asp-for="CreateDate" class="form-control" />
                        <span asp-validation-for="CreateDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="ShortDescription" class="control-label"></label>
                        <input asp-for="ShortDescription" class="form-control" />
                        <span asp-validation-for="ShortDescription" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TagsName" class="control-label"></label>
                        <input asp-for="TagsName" class="form-control" />
                        <span asp-validation-for="TagsName" class="text-danger"></span>
                    </div>

                </div>
            </div>
            <div class="row">
                 <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Title" class="control-label"></label>
                        <input asp-for="Title" class="form-control" />
                        <span asp-validation-for="Title" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="TellphoneNmber" class="control-label"></label>
                        <input asp-for="TellphoneNmber" class="form-control" />
                        <span asp-validation-for="TellphoneNmber" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="PictureAddress" class="control-label"></label>
                        <input asp-for="PictureAddress" class="form-control" />
                        <span asp-validation-for="PictureAddress" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="FullDescription" class="control-label"></label>
                        <input asp-for="FullDescription" class="form-control" />
                        <span asp-validation-for="FullDescription" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="دانان" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">گەڕانەوە بۆ لیست</a>
            </div>
        </form>
    </div>
</div>

WebsitePresentation/Areas/AdministratorArea/Views/WebsiteAdminsControls/Index.cshtml
@model IEnumerable<Model.WebsiteAdminsControl>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/AdministratorArea/Views/Shared/_Layout.cshtml";
    var imgaddress = "";
}

<h5>کۆنتڕۆڵی کاتی کارابوونی ئەدمینەکان<a asp-action="Create" class="fa fa-plus"></a></h5>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.Label("وێنە")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TellphoneNmber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timable)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            imgaddress = @"/Images/ImageAdmin/" + item.PictureAddress;
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    <img src="@imgaddress" style="width:30px;height:30px;border-radius:5px;">
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TellphoneNmber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timable)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id"class="fa fa-edit"> </a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="fa fa-book"> </a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="fa fa-trash"> </a>
                </td>
            </tr>
        }
    </tbody>
</table>